### PR TITLE
Updates to Custom metadata layouts and case record page 

### PR DESCRIPTION
**Pull request by vasanthid23**

### CODE REVIEW

**Comment by vasanthid23** [comment]
Hi @cgijeffolsen  @cgiSunilM  Here is the small PR to main to include custom meta data type layouts and also cosmetic updates to email template along with case record page to eliminate post deployment steps
Please review and approve.
cc @deepakmulamalla

**Comment by deepakmulamalla** [comment]
Hi @cgijeffolsen/ @cgiSunilM ,

Would you please approve this pr? So that we can initiate the deployment to Staging for Sprint-6 development.

Thanks,
Deepak Mulamalla
cc: @vasanthid23

**Review by cgijeffolsen — APPROVED** [review]
Approved @vasanthid23

**Comment by cgijeffolsen** [comment]
@RanadheerRG please review as the second approver these straightforward layout changes for the team. Thank you.

**Comment by deepakmulamalla** [comment]
Hey @RanadheerRG,

Could please at the changes and approve this pr? We are waiting for the deployment.

Thanks,
Deepak Mulamalla

**Review by RanadheerRG — APPROVED** [review]
Approved @vasanthid23 @NataliaNikishina

**Pull request merged**
