### PR TITLE
Changes related - Welcome email configuration for EDRD-Portal

### PR DESCRIPTION
**Pull request by deepakmulamalla**
Changes related - Welcome email configuration for EDRD-Portal

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
This is approved and it indepdent from SAT. @deepakmulamalla 
@RanadheerRG

**Review by NataliaNikishina — APPROVED** [review]
LGTM, Thanks!
cc: @deepakmulamalla

**Comment by deepakmulamalla** [comment]
Hi @RanadheerRG , can you approve this PR?

**Review by RanadheerRG — APPROVED** [review]
@deepakmulamalla  Approved

**Comment by RanadheerRG** [comment]
Confidential

Hi Deepak,

I have approved the PR. Please go ahead and merge it.

Thanks,
Rana

**Pull request merged**
