### PR TITLE
ESA-1395 changes to case origin descriptors

### PR DESCRIPTION
**Pull request by hlthAkennes**
Updated case owner label "phone" to "Phone / Voicemail"

### CODE REVIEW

**Comment by hlthAkennes** [comment]
Expected changes made to CaseOrigin.standardValueSet-meta.xml
i DO NOT KNOW why it added code changes to Special_Authority_Request.recordType-meta.xml  but maybe that's ok?

**Comment by janjulian** [comment]
@hlthAkennes this change might break a process builder that switches a case's owner to the urgent queue if origin is switched to `Phone`. Could you check this on your scratch org if you still have it?

**Comment by hlthAkennes** [comment]
Scratch org does not have case assignment rules in the drug manager, and interface does not allow for re-creation of those rules.  Solution if possible: mass-update drug rules for phone assignment to urgent queue to replace logic condition of Origin EQUALS Phone to origin CONTAINS phone, should pre-empt issue regardless of whether condition triggers off of API or label.

**Comment by janjulian** [comment]
@hlthAkennes fyi, i removed the record type file on your commit. every now and then certain configuration changes on salesforce toggle changes to other metadata as well. you can review these files and commit them as needed.

also, when create a new branch, you'll often want to start with the "latest" version of code in main. run these commands to create a branch from the latest code:

```
# switch to "main" branch
$ git checkout main 

# fetch new commits in remote "main" branch, and merge them to local "main" branch.
$ git pull 

# create a new branch from the current branch (main), and switch to it.
$ git checkout -b ESA-NEW-BRANCH
```

You may need to run these commands, before running above lines, to clean your local directory of any dirty files
```
# undo all un-committed file modifications
$ git reset --hard

$ remove any new files / folders that are not tracked by git
git clean -fd
```

**Comment by janjulian** [comment]
btw, i tested your change and it didn't break CBA rules or process builders that set owner to urgent if origin is phone.

**Pull request merged**
