### PR TITLE
Updated Patient Name Template Formula

### PR DESCRIPTION
**Pull request by anudishCGI**
Updated formula for Patient Name Template field 
Object : Case
Field : Patient Name (Template)

Original Formula:     <formula>Account.Person_Full_Name__c</formula>
Updated Formula:  <formula>Contact.FirstName + &apos; &apos; +  Contact.LastName</formula>

### CODE REVIEW

**Comment by herman-ovodov-cgi** [comment]
@anudishCGI @crystalz2022 given the origination of the data point, I would recommend reviewing the updated data flow with our business area, and confirm if the fix is a fit, and if deeper refactoring is required.

**Comment by anudishCGI** [comment]
@herman-ovodov-cgi @crystalz2022 
On further investigation, we see the references not proper for the Person Accounts in the template and patient identifier fields. 
Therefore, I updated the references following the lookup using Person Account.
Also, an update to case SA Layout to use account in place of contact for updating patient name (an incorrect reference earlier).
A thorough testing needed in Staging. SATCGIDev environment unit testing successful.

**Comment by herman-ovodov-cgi** [comment]
@anudishCGI I am good with the changes as long as the PO has reviewed them and confirmed that they are fine with the change and implications of the update,

**Comment by MeganWeston** [comment]
Thanks. this is fine to push to staging for testing.

**Pull request merged**
