### PR TITLE
EDRD API v60 Upgrade

### PR DESCRIPTION
**Pull request by deepakmulamalla**
API upgrade from v57 to v60

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
This PR completes the API update as expected. @deepakmulamalla 
cc @NataliaNikishina @RanadheerRG

**Comment by cgijeffolsen** [comment]
I have now approved this PR.


Thank you,

Jeff


________________________________

**Review by NataliaNikishina — APPROVED** [review]
@deepakmulamalla  The PR composition was validated. Thank you!
cc: @RanadheerRG

**Review by RanadheerRG — APPROVED** [review]
@deepakmulamalla  Approved.
Cc: @cgijeffolsen @NataliaNikishina

**Pull request merged**
