### PR TITLE
Changes related to ACR Dataload issues

### PR DESCRIPTION
**Pull request by deepakmulamalla**

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
Changse reviewed and meet expectations @deepakmulamalla 
@RanadheerRG @NataliaNikishina

**Review by RanadheerRG — APPROVED** [review]
@deepakmulamalla  Approved

**Comment by deepakmulamalla** [comment]
Hi @RanadheerRG / @cgijeffolsen ,

Thank you for approving PR-1353. Apologies for adding a new commit — I’ve included a very small update (i.e., adding accumulated strength in the forecast class) to address business UAT findings and ensure a smooth deployment using 2nd gen packaging. Could you please review and approve it?

@NataliaNikishina , once Jeff approves, could you also approve the PR and create the 2nd-generation package for me? I’ll handle the deployment to Staging and Full-copy from there.

Thanks for your understanding!

**Review by NataliaNikishina — APPROVED** [review]
@deepakmulamalla Approved

**Review by cgijeffolsen — APPROVED** [review]
Additions approved. Thank you @deepakmulamalla 
cc @RanadheerRG @NataliaNikishina

**Pull request merged**
