### PR TITLE
EDRD Phase1 defects fixing

### PR DESCRIPTION
**Pull request by deepakmulamalla**

### CODE REVIEW

**Review by ckleinacn — APPROVED** [review]

**Review by RanadheerRG — APPROVED** [review]
@deepakmulamalla Approved
cc: @cgijeffolsen

**Comment by deepakmulamalla** [comment]
@RanadheerRG , can I merge this PR? Or need to wait for other CGI review?

**Comment by RanadheerRG** [comment]
> @RanadheerRG , can I merge this PR? Or need to wait for other CGI review?

Please wait for Jeff's Approval

**Review by cgijeffolsen — APPROVED** [review]
These changes are appropriate and apprvoed. @deepakmulamalla
cc @ckleinacn @NataliaNikishina @RanadheerRG 

_Note the team added some SA sharing but it appears complimentary to existing functionality and is inline with the SA team requirements._

**Pull request merged**
