### PR TITLE
BCMOHAD-24466 && BCMOHAD-24614 || Updated the Visibility changes

### PR DESCRIPTION
**Pull request by RanadheerRG**
# Description

Updated the profile with Home app as a default app
Created the new custom Home app
Updated the permissions

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Deployment Tracker

dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml
dev-app-post/main/default/sharingRules/Account.sharingRules-meta.xml
force-app/main/default/applications/Home.app-meta.xml
force-app/main/default/objects/Account/listViews/All_Patients.listView-meta.xml
force-app/main/default/objects/Account/listViews/All_Providers.listView-meta.xml
force-app/main/default/objects/Case/listViews/Migraine_Queue_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Omalizumab_Case.listView-meta.xml
force-app/main/default/objects/Case/listViews/Service_Case_Case.listView-meta.xml

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
Approved @RanadheerRG 
cc @NataliaNikishina

**Review by cgijeffolsen — APPROVED** [review]
Approved update which now removes case visibility from role inheritance which can share case records which are app specific around apps due to the accounts being org-wide. @RanadheerRG 
cc @NataliaNikishina

**Review by cgijeffolsen — APPROVED** [review]
For collaboration cc @deepakmulamalla

Approved @RanadheerRG 
cc @NataliaNikishina

**Comment by cgijeffolsen** [comment]
@deepakmulamalla we are going to remove some of the redundant items in this PR to work you have done now in other tickets and also add the validation rules here with the present names. SAT (Megan) needs to review the renaming of these before it can be applied. @RanadheerRG

**Review by yashrohan-cgi — APPROVED** [review]

**Review by deepakmulamalla — APPROVED** [review]

**Review by NataliaNikishina — APPROVED** [review]
@RanadheerRG approved

**Pull request merged**
